### ISSUE TITLE
Implement Golang Project Monorepo

### ISSUE THREAD

**Issue by goosepart** [phamtai97/go-experienced-series#1]
I see you is a Experienced Golang Engineer, this will be great if you sharing how to do Golang Microservices in Monorepo with Hexagon or Clean Architecture

**Comment by phamtai97** [comment]
Sure, Building Go microservices in a monorepo with the Hexagon architecture can be a powerful way to organize your codebase and achieve modularity while keeping related services together. I think that we can organize the following structure:
```sh
├── go.mod
├── go.sum
├── microservice1
│   ├── cmd
│   │   └── main.go
│   ├── internal
│   │   ├── app
│   │   │   ├── controller
│   │   │   │   └── user_controller.go
│   │   │   ├── dto
│   │   │   │   └── user_dto.go
│   │   │   ├── entity
│   │   │   ├── model
│   │   │   │   ├── request
│   │   │   │   │   └── user_request.go
│   │   │   │   └── response
│   │   │   │       └── user_response.go
│   │   │   ├── port
│   │   │   │   ├── repository
│   │   │   │   │   ├── db_user_repository.go
│   │   │   │   │   └── user_repository.go
│   │   │   │   └── service
│   │   │   │       └── user_service.go
│   │   │   └── server
│   │   │       └── http_server.go
│   │   └── infra
│   │       ├── config
│   │       │   └── config.go
│   │       └── repository
│   │           ├── db.go
│   │           └── user_persistence.go
│   └── go.mod
├── microservice2
│   ├── cmd
│   │   └── main.go
│   ├── internal
│   │   ├── app
│   │   │   ├── controller
│   │   │   │   └── order_controller.go
│   │   │   ├── dto
│   │   │   │   └── order_dto.go
│   │   │   ├── entity
│   │   │   ├── model
│   │   │   │   ├── request
│   │   │   │   │   └── order_request.go
│   │   │   │   └── response
│   │   │   │       └── order_response.go
│   │   │   ├── port
│   │   │   │   ├── repository
│   │   │   │   │   ├── db_order_repository.go
│   │   │   │   │   └── order_repository.go
│   │   │   │   └── service
│   │   │   │       └── order_service.go
│   │   │   └── server
│   │   │       └── http_server.go
│   │   └── infra
│   │       ├── config
│   │       │   └── config.go
│   │       └── repository
│   │           ├── db.go
│   │           └── order_persistence.go
│   └── go.mod
...
```

By structuring the monorepo this way, you can maintain clear separation of concerns, keep each microservice's components organized, and ensure a clean and modular codebase following the Hexagonal architecture principles.

**Comment by goosepart** [comment]
Hmmm, What do you think about go workspace, I see in root folder you have the go.mod file. Or you want the resource like (entity, struct, helper func, etc) should be isolated?

**Comment by phamtai97** [comment]
Yes, I want to be isolated between them. We need to isolate resources (entities, structs, helper functions, etc.), it's a good practice to organize them within the project's directory structure. Each microservice or module should have its own directory, and resources specific to that microservice should reside within that directory. By organizing the resources within the respective microservice's directory, it ensures that each microservice has its own dedicated space, and it's less likely to introduce conflicts or confusion.

**Comment by goosepart** [comment]
What do you think about some reuseable code something like the database connection with the retry connect logic in the function make connection to the database: mysql, redis, postgresql, etc, I think this will be better if I have 1 module for common logic I just mention about (maybe not include entity, struct as well)

**Comment by phamtai97** [comment]
That's right. Creating a separate module or package for common logic is a good practice. However, it's essential to keep the shared package focused on truly common and reusable functionality. Avoid adding too many unrelated functionalities, as it may increase the package's complexity and make it harder to manage.

I often separate them to another repo as library, then importing this lib to my project.

**Comment by goosepart** [comment]
Thanks @phamtai97
